services: 
    frontend:
        image: store:latest
        environment: 
            - ProductEndpoint=http://backend:8080
        ports:
            - "32002:8080"
        depends_on: 
            - backend
    backend:
        image: products:latest
        ports: 
            - "32003:8080"